reg/music/urls.py
from django.conf.urls import url
from . import views

app_namespace = 'music'

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^registration/$', views.UserFormView.as_view(), name='registration'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/edit/$', views.AlbumEdit.as_view(), name='album-edit'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

reg/reg/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls', namespace='music')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reg/music/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=50)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.artist + ' - ' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

reg/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

reg/music/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from .models import Album, Song
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumEdit(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

reg/music/templates/music/album_confirm_delete.html
{% block base %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
    <form action="{% url 'music:index' %}">
        <input type="submit" value="<-Back" />
    </form>
{% endblock %}

reg/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block album_title %} Add new Album {% endblock %}
{% block body %}
    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-12 col-md-7">
              <div class="panel panel-default">
                  <div class="panel-body">
                      <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          {% include 'music/form-template.html' %}
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <button type="submit" class="btn btn-success"> Sumbit</button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
    </div>
{% endblock %}

reg/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      {% load staticfiles %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
      <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
      <meta charset="UTF-8">
      <title>{% block title %} Sliderr {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'music:index' %}"> Sliderr </a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Music
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log out
                    </a>
                </li>
            </ul>
        </div>
      </div>
  </nav>
  {% block body %}
  {% endblock %}
  </body>
</html>

reg/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Detail {% endblock %}
{% block body %}
    <img src={{ album.album_logo.url }} width="255" height="255">
    <h1> {{album.album_title }} </h1>
    <h3> {{album.artist}} </h3>
    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="https://vignette.wikia.nocookie.net/lhm/images/2/2e/Star.png/revision/latest?cb=20140812194111&path-prefix=ru" width="16" height="16">
        {% endif %}
        <br>
    {% endfor %}
    <a href="{% url 'music:album-edit' album.id %}">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Edit
    </a>
    <a href="{% url 'music:album-delete' album.id %}">
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp; Delete
    </a>
{% endblock %}

reg/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"> {{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field  }}</div>
    </div>
{% endfor %}

reg/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
    {% if all_albums %}
        <h3> Albums </h3>
        <ul>
            {% for album in all_albums %}
                <li><a href="{%  url 'music:detail' album.id %}"> {{album.album_title}} </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3> You don't have any albums </h3>
    {% endif %}
{% endblock %}

reg/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block album_title %} Registration {% endblock %}
{% block body %}
    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-12 col-md-7">
              <div class="panel panel-default">
                  <div class="panel-body">
                      <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          {% include 'music/form-template.html' %}
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <button type="submit" class="btn btn-success"> Register</button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
    </div>
{% endblock %}